[Match]
Architecture=arm64

[Output]
Format=disk
Output=image
ImageId=openSUSE-Tumbleweed-RaspberryPi-NoNewPrivs

[Content]
Packages=
	enable-no_new_privs
	run0-policy-wheel-auth-self
	patterns-images-raspberrypi

[Include]
Include=%D/../mkosi.generic
Include=%D/mkosi.tumbleweed
