[Content]
WithDocs=no
Packages=MicroOS-release
	MicroOS-release-appliance
        patterns-microos-basesystem
	patterns-microos-base-zypper
	patterns-microos-defaults
	patterns-microos-selinux
	zypp-excludedocs
	zypp-no-multiversion
