[Content]
#RootPassword=linux
WithDocs=yes
Packages=openSUSE-release
	openSUSE-release-appliance-custom
        patterns-base-base
	patterns-base-enhanced_base # openssh
        patterns-base-sw_management # zypper
	patterns-base-selinux
	snapper-zypp-plugin
        curl
	mdadm
# network
        iproute2
	iputils
        NetworkManager
# Recommends on Tumbleweed
	audit
	acl
	vim-small
	pam_pwquality
	cracklib-dict-small # Avoid the big 10MiB one
	#glibc-locale
	parted
	polkit-default-privs
	less
	man
	zypper-needs-restarting # Some deployment script use this (bsc#1173548)
