[Content]
Ssh=no
WithRecommends=no
Bootable=no
SELinuxRelabel=true
Packages=patterns-base-hardware
	live-add-yast-repos
	combustion
	jeos-firstboot
	kernel-default
	kernel-firmware-all
	systemd-repart-dracut
	account-utils
	zypp-no-recommends
	zypp-single-rpmtrans
# bootloader
	dracut
	systemd-boot
	sdbootutil
	sdbootutil-snapper
	shim
	uefi_mbr
	mokutil
	efibootmgr
	update-bootloader
# FDE
	cryptsetup
	device-mapper
	disk-encryption-tool
	dracut-pcr-signature
	sdbootutil-enroll
	sdbootutil-jeos-firstboot-enroll
# common
	group(mail) # needed by useradd bsc#1061838
	bash-completion
	dosfstools # For fscking ESP and XBOOTLDR partitions
	lsof # For zypper ps (bsc#1167553)
	qemu-guest-agent
	rdii-helper
	rsync
	sndiff
	system-group-wheel
	tar
	wget
RemovePackages=
	live-add-yast-repos
RemoveFiles=
	/init
	/var/adm
	/var/cache
	/var/crash
	/var/lib/ca-certificates
	/var/lib/zypp/AnonymousUniqueId
	/var/lib/systemd/random-seed
        /var/lock
        /var/run
        /var/spool
        /var/opt
