[Distribution]
Distribution=opensuse
Release=tumbleweed

[Output]
OutputDirectory=mkosi.output
Format=none
ImageVersion=0.0

[Content]
Bootable=no
Packages=
	NetworkManager
	account-utils
	acl
	audit
	bash-completion
	combustion
	cracklib-dict-small
	cryptsetup
	curl
	device-mapper
	disk-encryption-tool
	dosfstools
	dracut
	dracut-pcr-signature
	efibootmgr
	enable-no_new_privs
	group(mail)
	iproute2
	iputils
	jeos-firstboot
	kernel-default
	kernel-firmware-all
	less
	live-add-yast-repos
	lsof
	man
	mdadm
	mokutil
	openSUSE-release
	openSUSE-release-appliance-custom
	pam_pwquality
	parted
	patterns-base-base
	patterns-base-enhanced_base
	patterns-base-hardware
	patterns-base-selinux
	patterns-base-sw_management
	patterns-images-raspberrypi
	polkit-default-privs
	qemu-guest-agent
	rdii-helper
	rsync
	run0-policy-wheel-auth-self
	sdbootutil
	sdbootutil-enroll
	sdbootutil-jeos-firstboot-enroll
	sdbootutil-snapper
	shim
	snapper-zypp-plugin
	sndiff
	system-group-wheel
	systemd-boot
	systemd-repart-dracut
	tar
	uefi_mbr
	update-bootloader
	vim-small
	wget
	zypp-no-recommends
	zypp-single-rpmtrans
	zypper-needs-restarting
