[Match]
Architecture=arm64

[Output]
Format=disk
ImageId=openSUSE-MicroOS-RaspberryPi-Base

[Content]
Packages=
        patterns-images-raspberrypi

[Include]
Include=%D/../mkosi.raspberrypi
Include=%D/../mkosi.generic
Include=%D/mkosi.microos
