[Output]
Format=disk
ImageId=openSUSE-MicroOS-RaspberryPi-ContainerHost

[Content]
Packages=
	patterns-containers-container_runtime
        patterns-images-raspberrypi

[Include]
Include=%D/../mkosi.raspberrypi
Include=%D/../mkosi.generic
Include=%D/mkosi.microos

